### ISSUE TITLE
ModuleNotFoundError: No module named 'pluginbase._internalspace.

### ISSUE THREAD

**Issue by kuronekonano** [ovh/celery-director#124]
I use `director init examples/`
And `director db upgrade  `
Then...

```py
Usage: flask db upgrade [OPTIONS] [REVISION]

Error: While importing "director._auto", an ImportError was raised:

Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/xxx/.local/lib/python3.6/site-packages/director/_auto.py", line 6, in <module>
    app = create_app()
  File "/home/xxx/.local/lib/python3.6/site-packages/director/__init__.py", line 81, in create_app
    cel_workflows.init_app(app)
  File "/home/xxx/.local/lib/python3.6/site-packages/director/extensions.py", line 32, in init_app
    self.import_user_tasks()
  File "/home/xxx/.local/lib/python3.6/site-packages/director/extensions.py", line 69, in import_user_tasks
    ["__name__"],
  File "/home/xxx/.local/lib/python3.6/site-packages/pluginbase.py", line 439, in plugin_import
    fromlist, level)
ModuleNotFoundError: No module named 'pluginbase._internalspace._sp6a9eb6eb6274a2cf510c7f359d6ebf8e.tasks.group'; 'pluginbase._internalspace._sp6a9eb6eb6274a2cf510c7f359d6ebf8e.tasks' is not a package
```

**Comment by ncrocfer** [comment]
Did you export `DIRECTOR_HOME` env variable? See https://ovh.github.io/celery-director/quickstart/

**Comment by ncrocfer** [comment]
Without answer since January I close this issue. Please reopen another one if you still encounter this error.
